### ISSUE TITLE
[Question] How to set up development environment?

### ISSUE THREAD

**Issue by hashlin** [PopStackHack/mVoterAndroid#3]
Could you please provide any guideline on how to setup for development build? It would be very helpful for pull requests.

**Comment by vincent-paing** [comment]
I'm preparing a draft of Contribution guide. For API access, we can't share production environment, it would nice to have a mock or fake network written to use for development

**Comment by hashlin** [comment]
Thank you so much. It would be super helpful.

**Comment by vincent-paing** [comment]
Added a contributing guide and how to setup dev environment, can you check it and if it works on your end, I can close this and merge #4 as well

**Comment by hashlin** [comment]
I just try step by step of the guideline. App is up and running now.
