### ISSUE TITLE
UI Improvement : Party name text is cut off at the end while going to party page from candidate profile

### ISSUE THREAD

**Issue by hashlin** [PopStackHack/mVoterAndroid#8]
Party name text is cut off at the end while going to party page from candidate profile.

In screencast, the text UDP is cut off after animation, it is like 95% of the time. Sometimes it shows correctly.

![party-name](https://user-images.githubusercontent.com/7232905/95463624-faac2300-099e-11eb-835b-3982c6afdb56.gif)

**Comment by vincent-paing** [comment]
I think it's not being cut off. Abbreviation is separated into new `textView`. The animation could be improved though

**Comment by vincent-paing** [comment]
@hashlin  I couldn't replicate this issue. Can I get more information on your device model?

**Comment by hashlin** [comment]
My device is Xiaomi Mi A2.

The above commit seems to solve the issue.

**Comment by vincent-paing** [comment]
TIL: wrap content sometimes break the textview if you use transition API.
